// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpbDacUl5KNdt-wxkH6oIfEQ2P0uGEeqo',
    appId: '1:410818381594:web:0ef6a40f37ba86d2930ea3',
    messagingSenderId: '410818381594',
    projectId: 'finance-app-5b520',
    authDomain: 'finance-app-5b520.firebaseapp.com',
    databaseURL: 'https://finance-app-5b520-default-rtdb.firebaseio.com',
    storageBucket: 'finance-app-5b520.appspot.com',
    measurementId: 'G-T7GYFFTLQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYEklgy7DfvYwTZcZ_Vtf-Tk1CL0xvbbE',
    appId: '1:410818381594:android:b68447bade8b07e8930ea3',
    messagingSenderId: '410818381594',
    projectId: 'finance-app-5b520',
    databaseURL: 'https://finance-app-5b520-default-rtdb.firebaseio.com',
    storageBucket: 'finance-app-5b520.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKS3eZ8SahyCW0Ys0vO0WAvyfot923ft8',
    appId: '1:410818381594:ios:c65dd40179b41dd8930ea3',
    messagingSenderId: '410818381594',
    projectId: 'finance-app-5b520',
    databaseURL: 'https://finance-app-5b520-default-rtdb.firebaseio.com',
    storageBucket: 'finance-app-5b520.appspot.com',
    iosBundleId: 'com.example.budgetBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKS3eZ8SahyCW0Ys0vO0WAvyfot923ft8',
    appId: '1:410818381594:ios:5df744d41aea5909930ea3',
    messagingSenderId: '410818381594',
    projectId: 'finance-app-5b520',
    databaseURL: 'https://finance-app-5b520-default-rtdb.firebaseio.com',
    storageBucket: 'finance-app-5b520.appspot.com',
    iosBundleId: 'com.example.budgetBuddy.RunnerTests',
  );
}
